//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Clean.Care.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_CONTENT
    {
        public int ID { get; set; }
        public string MODULE { get; set; }
        public string SECTION_NAME { get; set; }
        public string HTML_SUB_HEADER1 { get; set; }
        public string HTML_SUB_HEADER2 { get; set; }
        public string HTML_VALUE { get; set; }
        public string IMAGE_URL1 { get; set; }
        public string IMAGE_URL2 { get; set; }
        public string IMAGE_URL3 { get; set; }
        public int SEQ { get; set; }
        public int STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
